# Generated by Django 4.0.7 on 2022-09-28 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_board_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='number',
        ),
    ]
