# Generated by Django 4.0.7 on 2022-09-23 14:54

import codi.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(blank=True, max_length=100, verbose_name='One Line Description')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Codi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='TITLE')),
                ('description', models.TextField(blank=True, verbose_name='Codi Description')),
                ('image', codi.fields.ThumbnailImageField(upload_to='codi/%Y/%m')),
                ('upload_dt', models.DateTimeField(auto_now_add=True, verbose_name='Upload Date')),
                ('url', models.URLField(verbose_name='site_url')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='codi.category')),
            ],
            options={
                'ordering': ('title',),
            },
        ),
    ]
